import 'dart:convert';
import 'dart:io';
import 'package:zulip/model/content_example_json.dart';
import 'model/content_test.dart';
import 'model/katex_test.dart';

Future<void> main() async {
  final contentExamples = <ContentExampleJson>[
    ContentExample.strong.toJsonSerializable(),
    ContentExample.deleted.toJsonSerializable(),
    ContentExample.emphasis.toJsonSerializable(),
    ContentExample.inlineCode.toJsonSerializable(),
    ContentExample.userMentionPlain.toJsonSerializable(),
    ContentExample.userMentionSilent.toJsonSerializable(),
    ContentExample.userMentionSilentClassOrderReversed.toJsonSerializable(),
    ContentExample.groupMentionPlain.toJsonSerializable(),
    ContentExample.groupMentionSilent.toJsonSerializable(),
    ContentExample.groupMentionSilentClassOrderReversed.toJsonSerializable(),
    ContentExample.channelWildcardMentionPlain.toJsonSerializable(),
    ContentExample.channelWildcardMentionSilent.toJsonSerializable(),
    ContentExample.channelWildcardMentionSilentClassOrderReversed.toJsonSerializable(),
    ContentExample.legacyChannelWildcardMentionPlain.toJsonSerializable(),
    ContentExample.legacyChannelWildcardMentionSilent.toJsonSerializable(),
    ContentExample.legacyChannelWildcardMentionSilentClassOrderReversed.toJsonSerializable(),
    ContentExample.topicMentionPlain.toJsonSerializable(),
    ContentExample.topicMentionSilent.toJsonSerializable(),
    ContentExample.topicMentionSilentClassOrderReversed.toJsonSerializable(),
    ContentExample.emojiUnicode.toJsonSerializable(),
    ContentExample.emojiUnicodeClassesFlipped.toJsonSerializable(),
    ContentExample.emojiUnicodeMultiCodepoint.toJsonSerializable(),
    ContentExample.emojiUnicodeLiteral.toJsonSerializable(),
    ContentExample.emojiCustom.toJsonSerializable(),
    ContentExample.emojiCustomInvalidUrl.toJsonSerializable(),
    ContentExample.emojiZulipExtra.toJsonSerializable(),
    ContentExample.mathInline.toJsonSerializable(),
    ContentExample.mathInlineUnknown.toJsonSerializable(),
    ContentExample.globalTime.toJsonSerializable(),
    ContentExample.messageLink.toJsonSerializable(),
    ContentExample.orderedListCustomStart.toJsonSerializable(),
    ContentExample.orderedListLargeStart.toJsonSerializable(),
    ContentExample.spoilerDefaultHeader.toJsonSerializable(),
    ContentExample.spoilerPlainCustomHeader.toJsonSerializable(),
    ContentExample.spoilerRichHeaderAndContent.toJsonSerializable(),
    ContentExample.spoilerHeaderHasImage.toJsonSerializable(),
    ContentExample.quotation.toJsonSerializable(),
    ContentExample.codeBlockPlain.toJsonSerializable(),
    ContentExample.codeBlockHighlightedShort.toJsonSerializable(),
    ContentExample.codeBlockHighlightedMultiline.toJsonSerializable(),
    ContentExample.codeBlockSpansWithMultipleClasses.toJsonSerializable(),
    ContentExample.codeBlockWithEmptyBody.toJsonSerializable(),
    ContentExample.codeBlockWithHighlightedLines.toJsonSerializable(),
    ContentExample.codeBlockWithUnknownSpanType.toJsonSerializable(),
    ContentExample.codeBlockFollowedByMultipleLineBreaks.toJsonSerializable(),
    ContentExample.mathBlock.toJsonSerializable(),
    ContentExample.mathBlockUnknown.toJsonSerializable(),
    ContentExample.mathBlocksMultipleInParagraph.toJsonSerializable(),
    ContentExample.mathBlockInQuote.toJsonSerializable(),
    ContentExample.mathBlocksMultipleInQuote.toJsonSerializable(),
    ContentExample.mathBlockBetweenImages.toJsonSerializable(),
    ContentExample.imageSingle.toJsonSerializable(),
    ContentExample.imageSingleNoDimensions.toJsonSerializable(),
    ContentExample.imageSingleNoThumbnail.toJsonSerializable(),
    ContentExample.imageSingleLoadingPlaceholder.toJsonSerializable(),
    ContentExample.imageSingleExternal.toJsonSerializable(),
    ContentExample.imageInvalidUrl.toJsonSerializable(),
    ContentExample.imageCluster.toJsonSerializable(),
    ContentExample.imageClusterNoThumbnails.toJsonSerializable(),
    ContentExample.imageClusterThenContent.toJsonSerializable(),
    ContentExample.imageMultipleClusters.toJsonSerializable(),
    ContentExample.imageInImplicitParagraph.toJsonSerializable(),
    ContentExample.imageClusterInImplicitParagraph.toJsonSerializable(),
    ContentExample.imageClusterInImplicitParagraphThenContent.toJsonSerializable(),
    ContentExample.videoEmbedYoutube.toJsonSerializable(),
    ContentExample.videoEmbedYoutubeClassesFlipped.toJsonSerializable(),
    ContentExample.videoEmbedVimeoPreviewDisabled.toJsonSerializable(),
    ContentExample.videoEmbedVimeo.toJsonSerializable(),
    ContentExample.videoEmbedVimeoClassesFlipped.toJsonSerializable(),
    ContentExample.videoInline.toJsonSerializable(),
    ContentExample.videoInlineClassesFlipped.toJsonSerializable(),
    ContentExample.audioInline.toJsonSerializable(),
    ContentExample.audioInlineNoTitle.toJsonSerializable(),
    ContentExample.websitePreviewSmoke.toJsonSerializable(),
    ContentExample.websitePreviewWithoutTitle.toJsonSerializable(),
    ContentExample.websitePreviewWithoutDescription.toJsonSerializable(),
    ContentExample.websitePreviewWithoutTitleOrDescription.toJsonSerializable(),
    ContentExample.legacyWebsitePreviewSmoke.toJsonSerializable(),
    ContentExample.tableWithSingleRow.toJsonSerializable(),
    ContentExample.tableWithMultipleRows.toJsonSerializable(),
    ContentExample.tableWithBoldAndItalicHeaders.toJsonSerializable(),
    ContentExample.tableWithLinksInCells.toJsonSerializable(),
    ContentExample.tableWithImage.toJsonSerializable(),
    ContentExample.tableWithoutAnyBodyCellsInMarkdown.toJsonSerializable(),
    ContentExample.tableMissingOneBodyColumnInMarkdown.toJsonSerializable(),
    ContentExample.tableWithDifferentTextAlignmentInColumns.toJsonSerializable(),
    ContentExample.tableWithLinkCenterAligned.toJsonSerializable(),
    ContentExample.thematicBreak.toJsonSerializable(),
  ];

  final katexExamples = <KatexExampleJson>[
    KatexExample.sizing.toJsonSerializable(),
    KatexExample.nestedSizing.toJsonSerializable(),
    KatexExample.delimsizing.toJsonSerializable(),
    KatexExample.spacing.toJsonSerializable(),
    KatexExample.vlistSuperscript.toJsonSerializable(),
    KatexExample.vlistSubscript.toJsonSerializable(),
    KatexExample.vlistSubAndSuperscript.toJsonSerializable(),
    KatexExample.vlistRaisebox.toJsonSerializable(),
    KatexExample.negativeMargin.toJsonSerializable(),
    KatexExample.katexLogo.toJsonSerializable(),
    KatexExample.vlistNegativeMargin.toJsonSerializable(),
    KatexExample.color.toJsonSerializable(),
    KatexExample.textColor.toJsonSerializable(),
    KatexExample.customColorMacro.toJsonSerializable(),
    KatexExample.phantom.toJsonSerializable(),
    KatexExample.bigOperators.toJsonSerializable(),
    KatexExample.colonEquals.toJsonSerializable(),
    KatexExample.nulldelimiter.toJsonSerializable(),
  ];

  final examples = ExportedExamples(
    contentExamples: contentExamples,
    katexExamples: katexExamples,
  );

  final outputFile = File('test_examples.json');
  await outputFile.writeAsString(JsonEncoder.withIndent('  ').convert(examples.toJson()));

  //print('✓ Exported ${contentExamples.length} content examples');
  //print('✓ Exported ${katexExamples.length} KaTeX examples');
  //print('✓ Written to ${outputFile.path}');
}