// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsIosNotifications(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashIosNotifications(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsIosNotifications(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsIosNotifications(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsIosNotifications(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsIosNotifications(lhsKey, rhsKey) {
          if deepEqualsIosNotifications(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsIosNotifications(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashIosNotifications(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashIosNotifications(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashIosNotifications(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashIosNotifications(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashIosNotifications(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashIosNotifications(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// The notification content of the incoming push notification.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NotificationContent: Hashable {
  /// The raw APNs payload of the push notification.
  var payload: [AnyHashable?: Any?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationContent? {
    let payload = pigeonVar_list[0] as! [AnyHashable?: Any?]

    return NotificationContent(
      payload: payload
    )
  }
  func toList() -> [Any?] {
    return [
      payload
    ]
  }
  static func == (lhs: NotificationContent, rhs: NotificationContent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsIosNotifications(lhs.payload, rhs.payload)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NotificationContent")
    deepHashIosNotifications(value: payload, hasher: &hasher)
  }
}

/// The improved notification content that will be displayed to the user.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ImprovedNotificationContent: Hashable {
  /// The new title to use for the notification.
  var title: String
  /// The new subtitle to use for the notification.
  var subtitle: String
  /// The new body to use for the notification.
  var body: String
  /// The internal data to attach with the new notification.
  ///
  /// This replaces the raw APNs payload that was initially set from
  /// the remote push notification.
  var userInfo: [String: Any?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImprovedNotificationContent? {
    let title = pigeonVar_list[0] as! String
    let subtitle = pigeonVar_list[1] as! String
    let body = pigeonVar_list[2] as! String
    let userInfo = pigeonVar_list[3] as! [String: Any?]

    return ImprovedNotificationContent(
      title: title,
      subtitle: subtitle,
      body: body,
      userInfo: userInfo
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      subtitle,
      body,
      userInfo,
    ]
  }
  static func == (lhs: ImprovedNotificationContent, rhs: ImprovedNotificationContent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsIosNotifications(lhs.title, rhs.title) && deepEqualsIosNotifications(lhs.subtitle, rhs.subtitle) && deepEqualsIosNotifications(lhs.body, rhs.body) && deepEqualsIosNotifications(lhs.userInfo, rhs.userInfo)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImprovedNotificationContent")
    deepHashIosNotifications(value: title, hasher: &hasher)
    deepHashIosNotifications(value: subtitle, hasher: &hasher)
    deepHashIosNotifications(value: body, hasher: &hasher)
    deepHashIosNotifications(value: userInfo, hasher: &hasher)
  }
}

private class IosNotificationsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NotificationContent.fromList(self.readValue() as! [Any?])
    case 130:
      return ImprovedNotificationContent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class IosNotificationsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NotificationContent {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ImprovedNotificationContent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class IosNotificationsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return IosNotificationsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return IosNotificationsPigeonCodecWriter(data: data)
  }
}

class IosNotificationsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = IosNotificationsPigeonCodec(readerWriter: IosNotificationsPigeonCodecReaderWriter())
}

/// Exposes an API from Dart code which can be called from Swift code.
///
/// An implementation of this interface should be passed to
/// [ZulipBinding.instance.setupIosNotifFlutterApi] (which wraps
/// [IosNotifFlutterApi.setUp]) to initialize this Pigeon API.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol IosNotifFlutterApiProtocol {
  /// Corresponds to `NotificationService.didReceive` in NotificationService.swift.
  ///
  /// Invoked when NotificationService is triggered by a remote push
  /// notification, with the notification content which will contain the APNs
  /// payload.
  ///
  /// The returned result should be the improved notification content that
  /// will be displayed to the user.
  ///
  /// See docs: https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension/didreceive(_:withcontenthandler:)
  func didReceivePushNotification(content contentArg: NotificationContent, completion: @escaping (Result<ImprovedNotificationContent, PigeonError>) -> Void)
}
class IosNotifFlutterApi: IosNotifFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: IosNotificationsPigeonCodec {
    return IosNotificationsPigeonCodec.shared
  }
  /// Corresponds to `NotificationService.didReceive` in NotificationService.swift.
  ///
  /// Invoked when NotificationService is triggered by a remote push
  /// notification, with the notification content which will contain the APNs
  /// payload.
  ///
  /// The returned result should be the improved notification content that
  /// will be displayed to the user.
  ///
  /// See docs: https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension/didreceive(_:withcontenthandler:)
  func didReceivePushNotification(content contentArg: NotificationContent, completion: @escaping (Result<ImprovedNotificationContent, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.zulip.IosNotifFlutterApi.didReceivePushNotification\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([contentArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! ImprovedNotificationContent
        completion(.success(result))
      }
    }
  }
}
