// Autogenerated from Pigeon (v26.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsIosNotifications(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsIosNotifications(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsIosNotifications(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashIosNotifications(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashIosNotifications(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashIosNotifications(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// The notification content of the incoming push notification.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NotificationContent: Hashable {
  /// The raw APNs payload of the push notification.
  var payload: [AnyHashable?: Any?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationContent? {
    let payload = pigeonVar_list[0] as! [AnyHashable?: Any?]

    return NotificationContent(
      payload: payload
    )
  }
  func toList() -> [Any?] {
    return [
      payload
    ]
  }
  static func == (lhs: NotificationContent, rhs: NotificationContent) -> Bool {
    return deepEqualsIosNotifications(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashIosNotifications(value: toList(), hasher: &hasher)
  }
}

/// The improved notification content that will be displayed to the user.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ImprovedNotificationContent: Hashable {
  /// The new title to use for the notification.
  var title: String
  /// The new subtitle to use for the notification.
  var subtitle: String
  /// The new body to use for the notification.
  var body: String
  /// The internal data to attach with the new notification.
  ///
  /// This replaces the raw APNs payload that was initially set from
  /// the remote push notification.
  var userInfo: [String: Any?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImprovedNotificationContent? {
    let title = pigeonVar_list[0] as! String
    let subtitle = pigeonVar_list[1] as! String
    let body = pigeonVar_list[2] as! String
    let userInfo = pigeonVar_list[3] as! [String: Any?]

    return ImprovedNotificationContent(
      title: title,
      subtitle: subtitle,
      body: body,
      userInfo: userInfo
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      subtitle,
      body,
      userInfo,
    ]
  }
  static func == (lhs: ImprovedNotificationContent, rhs: ImprovedNotificationContent) -> Bool {
    return deepEqualsIosNotifications(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashIosNotifications(value: toList(), hasher: &hasher)
  }
}

private class IosNotificationsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NotificationContent.fromList(self.readValue() as! [Any?])
    case 130:
      return ImprovedNotificationContent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class IosNotificationsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NotificationContent {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ImprovedNotificationContent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class IosNotificationsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return IosNotificationsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return IosNotificationsPigeonCodecWriter(data: data)
  }
}

class IosNotificationsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = IosNotificationsPigeonCodec(readerWriter: IosNotificationsPigeonCodecReaderWriter())
}

/// Exposes an API from Dart code which can be called from Swift code.
///
/// An implementation of this interface should be passed to
/// [ZulipBinding.instance.setupIosNotifFlutterApi] (which wraps
/// [IosNotifFlutterApi.setUp]) to initialize this Pigeon API.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol IosNotifFlutterApiProtocol {
  /// Corresponds to `NotificationService.didReceive` in NotificationService.swift.
  ///
  /// Invoked when NotificationService is triggered by a remote push
  /// notification, with the notification content which will contain the APNs
  /// payload.
  ///
  /// The returned result should be the improved notification content that
  /// will be displayed to the user.
  ///
  /// See docs: https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension/didreceive(_:withcontenthandler:)
  func didReceivePushNotification(content contentArg: NotificationContent, completion: @escaping (Result<ImprovedNotificationContent, PigeonError>) -> Void)
}
class IosNotifFlutterApi: IosNotifFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: IosNotificationsPigeonCodec {
    return IosNotificationsPigeonCodec.shared
  }
  /// Corresponds to `NotificationService.didReceive` in NotificationService.swift.
  ///
  /// Invoked when NotificationService is triggered by a remote push
  /// notification, with the notification content which will contain the APNs
  /// payload.
  ///
  /// The returned result should be the improved notification content that
  /// will be displayed to the user.
  ///
  /// See docs: https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension/didreceive(_:withcontenthandler:)
  func didReceivePushNotification(content contentArg: NotificationContent, completion: @escaping (Result<ImprovedNotificationContent, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.zulip.IosNotifFlutterApi.didReceivePushNotification\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([contentArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! ImprovedNotificationContent
        completion(.success(result))
      }
    }
  }
}
