// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.zulip.flutter.notifications

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NotificationsPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class NotificationDataFromLaunch (
  /**
   * The raw payload that is attached to the notification,
   * holding the information required to carry out the navigation.
   *
   * See [NotificationHostApi.getNotificationDataFromLaunch].
   */
  val payload: Map<Any?, Any?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationDataFromLaunch {
      val payload = pigeonVar_list[0] as Map<Any?, Any?>
      return NotificationDataFromLaunch(payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NotificationDataFromLaunch
    return NotificationsPigeonUtils.deepEquals(this.payload, other.payload)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NotificationsPigeonUtils.deepHash(this.payload)
    return result
  }
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class NotificationTapEvent 
/**
 * On iOS, an event emitted when a notification is tapped.
 *
 * See [notificationTapEvents].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IosNotificationTapEvent (
  /**
   * The iOS APNs payload of the notification.
   *
   * See [notificationTapEvents].
   */
  val payload: Map<Any?, Any?>
) : NotificationTapEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IosNotificationTapEvent {
      val payload = pigeonVar_list[0] as Map<Any?, Any?>
      return IosNotificationTapEvent(payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IosNotificationTapEvent
    return NotificationsPigeonUtils.deepEquals(this.payload, other.payload)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NotificationsPigeonUtils.deepHash(this.payload)
    return result
  }
}

/**
 * On Android, an event emitted when a notification is tapped.
 *
 * See [notificationTapEvents].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidNotificationTapEvent (
  /**
   * The intent data URL of the notification.
   *
   * This is an internal URL that is generated using
   * `NotificationOpenPayload.buildAndroidNotificationUrl` while creating the
   * notification during `NotificationDisplayManager._onNotifPayloadNewMessage`.
   *
   * See [notificationTapEvents].
   */
  val dataUrl: String
) : NotificationTapEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidNotificationTapEvent {
      val dataUrl = pigeonVar_list[0] as String
      return AndroidNotificationTapEvent(dataUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dataUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidNotificationTapEvent
    return NotificationsPigeonUtils.deepEquals(this.dataUrl, other.dataUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NotificationsPigeonUtils.deepHash(this.dataUrl)
    return result
  }
}
private open class NotificationsPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationDataFromLaunch.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IosNotificationTapEvent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidNotificationTapEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NotificationDataFromLaunch -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is IosNotificationTapEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AndroidNotificationTapEvent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val NotificationsPigeonMethodCodec = StandardMethodCodec(NotificationsPigeonCodec())

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NotificationHostApi {
  /**
   * Retrieves notification data if the app was launched by tapping on a notification.
   *
   * Returns `launchOptions.remoteNotification`,
   * which is the raw APNs data dictionary
   * if the app launch was opened by a notification tap,
   * else null. See Apple doc:
   *   https://developer.apple.com/documentation/uikit/uiapplication/launchoptionskey/remotenotification
   */
  fun getNotificationDataFromLaunch(): NotificationDataFromLaunch?

  companion object {
    /** The codec used by NotificationHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NotificationsPigeonCodec()
    }
    /** Sets up an instance of `NotificationHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NotificationHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.NotificationHostApi.getNotificationDataFromLaunch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNotificationDataFromLaunch())
            } catch (exception: Throwable) {
              NotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class NotificationsPigeonStreamHandler<T>(
    val wrapper: NotificationsPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface NotificationsPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/**
 * An event stream that emits a notification payload
 * when a notification is tapped.
 *
 * On iOS, emits [IosNotificationTapEvent] when
 * `userNotificationCenter(_:didReceive:withCompletionHandler:)` gets
 * called, indicating that the user has tapped on a notification. The
 * emitted event carries a payload which will be the raw APNs data
 * dictionary from the `UNNotificationResponse` passed to that method.
 *
 * On Android, emits [AndroidNotificationTapEvent] when the initial launch
 * intent (`MainActivity.intent`) or the intent received via
 * `MainActivity.onNewIntent` is an ACTION_VIEW intent and the associated
 * data URL has the "zulip" scheme, and "notification" authority. The
 * emitted event will carry the intent data URL.
 */
abstract class NotificationTapEventsStreamHandler : NotificationsPigeonEventChannelWrapper<NotificationTapEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: NotificationTapEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.zulip.NotificationEventChannelApi.notificationTapEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = NotificationsPigeonStreamHandler<NotificationTapEvent>(streamHandler)
      EventChannel(messenger, channelName, NotificationsPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from NotificationsPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<NotificationTapEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
