// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.zulip.flutter.notifications

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NotificationsPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class NotificationDataFromLaunch (
  /**
   * The raw payload that is attached to the notification,
   * holding the information required to carry out the navigation.
   *
   * See [NotificationHostApi.getNotificationDataFromLaunch].
   */
  val payload: Map<Any?, Any?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationDataFromLaunch {
      val payload = pigeonVar_list[0] as Map<Any?, Any?>
      return NotificationDataFromLaunch(payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NotificationDataFromLaunch) {
      return false
    }
    if (this === other) {
      return true
    }
    return NotificationsPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class NotificationTapEvent 
/**
 * On iOS, an event emitted when a notification is tapped.
 *
 * See [notificationTapEvents].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IosNotificationTapEvent (
  /**
   * The iOS APNs payload of the notification.
   *
   * See [notificationTapEvents].
   */
  val payload: Map<Any?, Any?>
) : NotificationTapEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IosNotificationTapEvent {
      val payload = pigeonVar_list[0] as Map<Any?, Any?>
      return IosNotificationTapEvent(payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is IosNotificationTapEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return NotificationsPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * On Android, an event emitted when a notification is tapped.
 *
 * See [notificationTapEvents].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidNotificationTapEvent (
  /**
   * The intent data URL of the notification.
   *
   * This is an internal URL that is generated using
   * `NotificationOpenPayload.buildAndroidNotificationUrl` while creating the
   * notification during `NotificationDisplayManager._onMessageFcmMessage`.
   *
   * See [notificationTapEvents].
   */
  val dataUrl: String
) : NotificationTapEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidNotificationTapEvent {
      val dataUrl = pigeonVar_list[0] as String
      return AndroidNotificationTapEvent(dataUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dataUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AndroidNotificationTapEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return NotificationsPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class NotificationsPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationDataFromLaunch.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IosNotificationTapEvent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidNotificationTapEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NotificationDataFromLaunch -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is IosNotificationTapEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AndroidNotificationTapEvent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val NotificationsPigeonMethodCodec = StandardMethodCodec(NotificationsPigeonCodec())

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NotificationHostApi {
  /**
   * Retrieves notification data if the app was launched by tapping on a notification.
   *
   * Returns `launchOptions.remoteNotification`,
   * which is the raw APNs data dictionary
   * if the app launch was opened by a notification tap,
   * else null. See Apple doc:
   *   https://developer.apple.com/documentation/uikit/uiapplication/launchoptionskey/remotenotification
   */
  fun getNotificationDataFromLaunch(): NotificationDataFromLaunch?

  companion object {
    /** The codec used by NotificationHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NotificationsPigeonCodec()
    }
    /** Sets up an instance of `NotificationHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NotificationHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.NotificationHostApi.getNotificationDataFromLaunch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNotificationDataFromLaunch())
            } catch (exception: Throwable) {
              NotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class NotificationsPigeonStreamHandler<T>(
    val wrapper: NotificationsPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface NotificationsPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/**
 * An event stream that emits a notification payload
 * when a notification is tapped.
 *
 * On iOS, emits [IosNotificationTapEvent] when
 * `userNotificationCenter(_:didReceive:withCompletionHandler:)` gets
 * called, indicating that the user has tapped on a notification. The
 * emitted event carries a payload which will be the raw APNs data
 * dictionary from the `UNNotificationResponse` passed to that method.
 *
 * On Android, emits [AndroidNotificationTapEvent] when the initial launch
 * intent (`MainActivity.intent`) or the intent received via
 * `MainActivity.onNewIntent` is an ACTION_VIEW intent and the associated
 * data URL has the "zulip" scheme, and "notification" authority. The
 * emitted event will carry the intent data URL.
 */
abstract class NotificationTapEventsStreamHandler : NotificationsPigeonEventChannelWrapper<NotificationTapEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: NotificationTapEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.zulip.NotificationEventChannelApi.notificationTapEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = NotificationsPigeonStreamHandler<NotificationTapEvent>(streamHandler)
      EventChannel(messenger, channelName, NotificationsPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
