# For docs on this file, see:
#   https://dart.dev/tools/analysis
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Skip analysis on Pigeon-generated code, because it currently
    # triggers some stylistic lints and they aren't actionable for us.
    # (Some lints could signal a bug, which would be good to catch...
    # but typically those are lints Flutter upstream keeps enabled, so
    # if Pigeon tripped them it'd immediately get caught.)
    # TODO(pigeon) re-enable lints once clean: https://github.com/flutter/flutter/issues/145633
    - lib/host/*.g.dart

  language:
    # TODO(#719): Enable these strict-* options.
    # strict-casts: true
    strict-inference: true
    # strict-raw-types: true

linter:
  # For a list of all available lints, with docs, see:
  #   https://dart-lang.github.io/linter/lints/index.html.
  rules:
    no_literal_bool_comparisons: true
    prefer_relative_imports: true
