targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - constant_identifier_names
            # https://github.com/google/json_serializable.dart/issues/625
            - unnecessary_cast
