# Docs on this config file:
#   https://docs.flutter.dev/ui/accessibility-and-localization/internationalization#configuring-the-l10nyaml-file

arb-dir: assets/l10n
output-dir: lib/generated/l10n
template-arb-file: app_en.arb
required-resource-attributes: true
output-localization-file: zulip_localizations.dart
untranslated-messages-file: build/untranslated_messages.json
output-class: ZulipLocalizations
preferred-supported-locales: [ en ]
nullable-getter: false
