// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.zulip.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AndroidNotificationsPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Corresponds to `androidx.core.app.NotificationChannelCompat`
 *
 * See: https://developer.android.com/reference/androidx/core/app/NotificationChannelCompat
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NotificationChannel (
  val id: String,
  /**
   * Specifies the importance level of notifications
   * to be posted on this channel.
   *
   * Must be a valid constant from [NotificationImportance].
   */
  val importance: Long,
  val name: String? = null,
  val lightsEnabled: Boolean? = null,
  val soundUrl: String? = null,
  val vibrationPattern: LongArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationChannel {
      val id = pigeonVar_list[0] as String
      val importance = pigeonVar_list[1] as Long
      val name = pigeonVar_list[2] as String?
      val lightsEnabled = pigeonVar_list[3] as Boolean?
      val soundUrl = pigeonVar_list[4] as String?
      val vibrationPattern = pigeonVar_list[5] as LongArray?
      return NotificationChannel(id, importance, name, lightsEnabled, soundUrl, vibrationPattern)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      importance,
      name,
      lightsEnabled,
      soundUrl,
      vibrationPattern,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NotificationChannel
    return AndroidNotificationsPigeonUtils.deepEquals(this.id, other.id) && AndroidNotificationsPigeonUtils.deepEquals(this.importance, other.importance) && AndroidNotificationsPigeonUtils.deepEquals(this.name, other.name) && AndroidNotificationsPigeonUtils.deepEquals(this.lightsEnabled, other.lightsEnabled) && AndroidNotificationsPigeonUtils.deepEquals(this.soundUrl, other.soundUrl) && AndroidNotificationsPigeonUtils.deepEquals(this.vibrationPattern, other.vibrationPattern)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.id)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.importance)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.name)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.lightsEnabled)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.soundUrl)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.vibrationPattern)
    return result
  }
}

/**
 * Corresponds to `android.content.Intent`
 *
 * See:
 *   https://developer.android.com/reference/android/content/Intent
 *   https://developer.android.com/reference/android/content/Intent#Intent(java.lang.String,%20android.net.Uri,%20android.content.Context,%20java.lang.Class%3C?%3E)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidIntent (
  val action: String,
  val dataUrl: String,
  /** A combination of flags from [IntentFlag]. */
  val flags: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidIntent {
      val action = pigeonVar_list[0] as String
      val dataUrl = pigeonVar_list[1] as String
      val flags = pigeonVar_list[2] as Long
      return AndroidIntent(action, dataUrl, flags)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      action,
      dataUrl,
      flags,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidIntent
    return AndroidNotificationsPigeonUtils.deepEquals(this.action, other.action) && AndroidNotificationsPigeonUtils.deepEquals(this.dataUrl, other.dataUrl) && AndroidNotificationsPigeonUtils.deepEquals(this.flags, other.flags)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.action)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.dataUrl)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.flags)
    return result
  }
}

/**
 * Corresponds to `android.app.PendingIntent`.
 *
 * See: https://developer.android.com/reference/android/app/PendingIntent
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PendingIntent (
  val requestCode: Long,
  val intent: AndroidIntent,
  /**
   * A combination of flags from [PendingIntent.flags], and others associated
   * with `Intent`; see Android docs for `PendingIntent.getActivity`.
   */
  val flags: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PendingIntent {
      val requestCode = pigeonVar_list[0] as Long
      val intent = pigeonVar_list[1] as AndroidIntent
      val flags = pigeonVar_list[2] as Long
      return PendingIntent(requestCode, intent, flags)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestCode,
      intent,
      flags,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PendingIntent
    return AndroidNotificationsPigeonUtils.deepEquals(this.requestCode, other.requestCode) && AndroidNotificationsPigeonUtils.deepEquals(this.intent, other.intent) && AndroidNotificationsPigeonUtils.deepEquals(this.flags, other.flags)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.requestCode)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.intent)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.flags)
    return result
  }
}

/**
 * Corresponds to `androidx.core.app.NotificationCompat.InboxStyle`
 *
 * See: https://developer.android.com/reference/androidx/core/app/NotificationCompat.InboxStyle
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InboxStyle (
  val summaryText: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InboxStyle {
      val summaryText = pigeonVar_list[0] as String
      return InboxStyle(summaryText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      summaryText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InboxStyle
    return AndroidNotificationsPigeonUtils.deepEquals(this.summaryText, other.summaryText)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.summaryText)
    return result
  }
}

/**
 * Corresponds to `androidx.core.app.Person`
 *
 * See: https://developer.android.com/reference/androidx/core/app/Person
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Person (
  /**
   * An icon for this person.
   *
   * This should be compressed image data, in a format to be passed
   * to `androidx.core.graphics.drawable.IconCompat.createWithData`.
   * Supported formats include JPEG, PNG, and WEBP.
   *
   * See:
   *  https://developer.android.com/reference/androidx/core/graphics/drawable/IconCompat#createWithData(byte[],int,int)
   */
  val iconBitmap: ByteArray? = null,
  val key: String,
  val name: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Person {
      val iconBitmap = pigeonVar_list[0] as ByteArray?
      val key = pigeonVar_list[1] as String
      val name = pigeonVar_list[2] as String
      return Person(iconBitmap, key, name)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      iconBitmap,
      key,
      name,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Person
    return AndroidNotificationsPigeonUtils.deepEquals(this.iconBitmap, other.iconBitmap) && AndroidNotificationsPigeonUtils.deepEquals(this.key, other.key) && AndroidNotificationsPigeonUtils.deepEquals(this.name, other.name)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.iconBitmap)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.key)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.name)
    return result
  }
}

/**
 * Corresponds to `androidx.core.app.NotificationCompat.MessagingStyle.Message`
 *
 * See: https://developer.android.com/reference/androidx/core/app/NotificationCompat.MessagingStyle.Message
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MessagingStyleMessage (
  val text: String,
  val timestampMs: Long,
  val person: Person
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessagingStyleMessage {
      val text = pigeonVar_list[0] as String
      val timestampMs = pigeonVar_list[1] as Long
      val person = pigeonVar_list[2] as Person
      return MessagingStyleMessage(text, timestampMs, person)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      timestampMs,
      person,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MessagingStyleMessage
    return AndroidNotificationsPigeonUtils.deepEquals(this.text, other.text) && AndroidNotificationsPigeonUtils.deepEquals(this.timestampMs, other.timestampMs) && AndroidNotificationsPigeonUtils.deepEquals(this.person, other.person)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.text)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.timestampMs)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.person)
    return result
  }
}

/**
 * Corresponds to `androidx.core.app.NotificationCompat.MessagingStyle`
 *
 * See: https://developer.android.com/reference/androidx/core/app/NotificationCompat.MessagingStyle
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MessagingStyle (
  val user: Person,
  val conversationTitle: String? = null,
  val messages: List<MessagingStyleMessage>,
  val isGroupConversation: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessagingStyle {
      val user = pigeonVar_list[0] as Person
      val conversationTitle = pigeonVar_list[1] as String?
      val messages = pigeonVar_list[2] as List<MessagingStyleMessage>
      val isGroupConversation = pigeonVar_list[3] as Boolean
      return MessagingStyle(user, conversationTitle, messages, isGroupConversation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      user,
      conversationTitle,
      messages,
      isGroupConversation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MessagingStyle
    return AndroidNotificationsPigeonUtils.deepEquals(this.user, other.user) && AndroidNotificationsPigeonUtils.deepEquals(this.conversationTitle, other.conversationTitle) && AndroidNotificationsPigeonUtils.deepEquals(this.messages, other.messages) && AndroidNotificationsPigeonUtils.deepEquals(this.isGroupConversation, other.isGroupConversation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.user)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.conversationTitle)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.messages)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.isGroupConversation)
    return result
  }
}

/**
 * Corresponds to `android.app.Notification`
 *
 * See: https://developer.android.com/reference/kotlin/android/app/Notification
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Notification (
  val group: String,
  val extras: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Notification {
      val group = pigeonVar_list[0] as String
      val extras = pigeonVar_list[1] as Map<String, String>
      return Notification(group, extras)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      group,
      extras,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Notification
    return AndroidNotificationsPigeonUtils.deepEquals(this.group, other.group) && AndroidNotificationsPigeonUtils.deepEquals(this.extras, other.extras)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.group)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.extras)
    return result
  }
}

/**
 * Corresponds to `android.service.notification.StatusBarNotification`
 *
 * See: https://developer.android.com/reference/android/service/notification/StatusBarNotification
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StatusBarNotification (
  val id: Long,
  val tag: String,
  val notification: Notification
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StatusBarNotification {
      val id = pigeonVar_list[0] as Long
      val tag = pigeonVar_list[1] as String
      val notification = pigeonVar_list[2] as Notification
      return StatusBarNotification(id, tag, notification)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      tag,
      notification,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StatusBarNotification
    return AndroidNotificationsPigeonUtils.deepEquals(this.id, other.id) && AndroidNotificationsPigeonUtils.deepEquals(this.tag, other.tag) && AndroidNotificationsPigeonUtils.deepEquals(this.notification, other.notification)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.id)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.tag)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.notification)
    return result
  }
}

/**
 * Represents details about a notification sound stored in the
 * shared media store.
 *
 * Returned as a list entry by
 * [AndroidNotificationHostApi.listStoredSoundsInNotificationsDirectory].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StoredNotificationSound (
  /** The display name of the sound file. */
  val fileName: String,
  /**
   * Specifies whether this file was created by the app.
   *
   * It is true if the `MediaStore.Audio.Media.OWNER_PACKAGE_NAME` key in the
   * metadata matches the app's package name.
   */
  val isOwned: Boolean,
  /** A `content://…` URL pointing to the sound file. */
  val contentUrl: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StoredNotificationSound {
      val fileName = pigeonVar_list[0] as String
      val isOwned = pigeonVar_list[1] as Boolean
      val contentUrl = pigeonVar_list[2] as String
      return StoredNotificationSound(fileName, isOwned, contentUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fileName,
      isOwned,
      contentUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StoredNotificationSound
    return AndroidNotificationsPigeonUtils.deepEquals(this.fileName, other.fileName) && AndroidNotificationsPigeonUtils.deepEquals(this.isOwned, other.isOwned) && AndroidNotificationsPigeonUtils.deepEquals(this.contentUrl, other.contentUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.fileName)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.isOwned)
    result = 31 * result + AndroidNotificationsPigeonUtils.deepHash(this.contentUrl)
    return result
  }
}
private open class AndroidNotificationsPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationChannel.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidIntent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PendingIntent.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InboxStyle.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Person.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessagingStyleMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessagingStyle.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Notification.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StatusBarNotification.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StoredNotificationSound.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NotificationChannel -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AndroidIntent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PendingIntent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is InboxStyle -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is Person -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MessagingStyleMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is MessagingStyle -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is Notification -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is StatusBarNotification -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is StoredNotificationSound -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AndroidNotificationHostApi {
  /**
   * Corresponds to `androidx.core.app.NotificationManagerCompat.createNotificationChannel`.
   *
   * See: https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat#createNotificationChannel(androidx.core.app.NotificationChannelCompat)
   */
  fun createNotificationChannel(channel: NotificationChannel)
  /**
   * Corresponds to `androidx.core.app.NotificationManagerCompat.getNotificationChannelsCompat`.
   *
   * See: https://developer.android.com/reference/kotlin/androidx/core/app/NotificationManagerCompat#getNotificationChannelsCompat()
   */
  fun getNotificationChannels(): List<NotificationChannel>
  /**
   * Corresponds to `androidx.core.app.NotificationManagerCompat.deleteNotificationChannel`
   *
   * See: https://developer.android.com/reference/kotlin/androidx/core/app/NotificationManagerCompat#deleteNotificationChannel(java.lang.String)
   */
  fun deleteNotificationChannel(channelId: String)
  /**
   * The list of notification sound files present under `Notifications/Zulip/`
   * in the device's shared media storage,
   * found with `android.content.ContentResolver.query`.
   *
   * This is a complex ad-hoc method.
   * For detailed behavior, see its implementation.
   *
   * Requires minimum of Android 10 (API 29) or higher.
   *
   * See: https://developer.android.com/reference/android/content/ContentResolver#query(android.net.Uri,%20java.lang.String[],%20java.lang.String,%20java.lang.String[],%20java.lang.String)
   */
  fun listStoredSoundsInNotificationsDirectory(): List<StoredNotificationSound>
  /**
   * Wraps `android.content.ContentResolver.insert` combined with
   * `android.content.ContentResolver.openOutputStream` and
   * `android.content.res.Resources.openRawResource`.
   *
   * Copies a raw resource audio file to `Notifications/Zulip/`
   * directory in device's shared media storage. Returns the URL
   * of the target file in media store.
   *
   * Requires minimum of Android 10 (API 29) or higher.
   *
   * See:
   *   https://developer.android.com/reference/android/content/ContentResolver#insert(android.net.Uri,%20android.content.ContentValues)
   *   https://developer.android.com/reference/android/content/ContentResolver#openOutputStream(android.net.Uri)
   *   https://developer.android.com/reference/android/content/res/Resources#openRawResource(int)
   */
  fun copySoundResourceToMediaStore(targetFileDisplayName: String, sourceResourceName: String): String
  /**
   * Corresponds to `android.app.NotificationManager.notify`,
   * combined with `androidx.core.app.NotificationCompat.Builder`.
   *
   * The arguments `tag` and `id` go to the `notify` call.
   * The rest go to method calls on the builder.
   *
   * The `color` should be in the form 0xAARRGGBB.
   * See [ColorExtension.argbInt].
   *
   * The `smallIconResourceName` is passed to `android.content.res.Resources.getIdentifier`
   * to get a resource ID to pass to `Builder.setSmallIcon`.
   * Whatever name is passed there must appear in keep.xml too:
   * see https://github.com/zulip/zulip-flutter/issues/528 .
   *
   * See:
   *   https://developer.android.com/reference/kotlin/android/app/NotificationManager.html#notify
   *   https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder
   */
  fun notify(tag: String?, id: Long, autoCancel: Boolean?, channelId: String, color: Long?, contentIntent: PendingIntent?, contentText: String?, contentTitle: String?, extras: Map<String, String>?, groupKey: String?, inboxStyle: InboxStyle?, isGroupSummary: Boolean?, messagingStyle: MessagingStyle?, number: Long?, smallIconResourceName: String?)
  /**
   * Wraps `androidx.core.app.NotificationManagerCompat.getActiveNotifications`,
   * combined with `androidx.core.app.NotificationCompat.MessagingStyle.extractMessagingStyleFromNotification`.
   *
   * Returns the messaging style, if any, of an active notification
   * that has tag `tag`.  If there are several such notifications,
   * an arbitrary one of them is used.
   * Returns null if there are no such notifications.
   *
   * See:
   *   https://developer.android.com/reference/kotlin/androidx/core/app/NotificationManagerCompat#getActiveNotifications()
   *   https://developer.android.com/reference/kotlin/androidx/core/app/NotificationCompat.MessagingStyle#extractMessagingStyleFromNotification(android.app.Notification)
   */
  fun getActiveNotificationMessagingStyleByTag(tag: String): MessagingStyle?
  /**
   * Corresponds to `androidx.core.app.NotificationManagerCompat.getActiveNotifications`.
   *
   * The keys of entries to fetch from notification's extras bundle must be
   * specified in the [desiredExtras] list. If this list is empty, then
   * [Notifications.extras] will also be empty. If value of the matched entry
   * is not of type string or is null, then that entry will be skipped.
   *
   * See: https://developer.android.com/reference/kotlin/androidx/core/app/NotificationManagerCompat?hl=en#getActiveNotifications()
   */
  fun getActiveNotifications(desiredExtras: List<String>): List<StatusBarNotification>
  /**
   * Corresponds to `androidx.core.app.NotificationManagerCompat.cancel`.
   *
   * See: https://developer.android.com/reference/kotlin/androidx/core/app/NotificationManagerCompat?hl=en#cancel(java.lang.String,int)
   */
  fun cancel(tag: String?, id: Long)

  companion object {
    /** The codec used by AndroidNotificationHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AndroidNotificationsPigeonCodec()
    }
    /** Sets up an instance of `AndroidNotificationHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AndroidNotificationHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.AndroidNotificationHostApi.createNotificationChannel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val channelArg = args[0] as NotificationChannel
            val wrapped: List<Any?> = try {
              api.createNotificationChannel(channelArg)
              listOf(null)
            } catch (exception: Throwable) {
              AndroidNotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.AndroidNotificationHostApi.getNotificationChannels$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNotificationChannels())
            } catch (exception: Throwable) {
              AndroidNotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.AndroidNotificationHostApi.deleteNotificationChannel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val channelIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.deleteNotificationChannel(channelIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              AndroidNotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.AndroidNotificationHostApi.listStoredSoundsInNotificationsDirectory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listStoredSoundsInNotificationsDirectory())
            } catch (exception: Throwable) {
              AndroidNotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.AndroidNotificationHostApi.copySoundResourceToMediaStore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val targetFileDisplayNameArg = args[0] as String
            val sourceResourceNameArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.copySoundResourceToMediaStore(targetFileDisplayNameArg, sourceResourceNameArg))
            } catch (exception: Throwable) {
              AndroidNotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.AndroidNotificationHostApi.notify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String?
            val idArg = args[1] as Long
            val autoCancelArg = args[2] as Boolean?
            val channelIdArg = args[3] as String
            val colorArg = args[4] as Long?
            val contentIntentArg = args[5] as PendingIntent?
            val contentTextArg = args[6] as String?
            val contentTitleArg = args[7] as String?
            val extrasArg = args[8] as Map<String, String>?
            val groupKeyArg = args[9] as String?
            val inboxStyleArg = args[10] as InboxStyle?
            val isGroupSummaryArg = args[11] as Boolean?
            val messagingStyleArg = args[12] as MessagingStyle?
            val numberArg = args[13] as Long?
            val smallIconResourceNameArg = args[14] as String?
            val wrapped: List<Any?> = try {
              api.notify(tagArg, idArg, autoCancelArg, channelIdArg, colorArg, contentIntentArg, contentTextArg, contentTitleArg, extrasArg, groupKeyArg, inboxStyleArg, isGroupSummaryArg, messagingStyleArg, numberArg, smallIconResourceNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              AndroidNotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.AndroidNotificationHostApi.getActiveNotificationMessagingStyleByTag$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getActiveNotificationMessagingStyleByTag(tagArg))
            } catch (exception: Throwable) {
              AndroidNotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.AndroidNotificationHostApi.getActiveNotifications$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val desiredExtrasArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              listOf(api.getActiveNotifications(desiredExtrasArg))
            } catch (exception: Throwable) {
              AndroidNotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zulip.AndroidNotificationHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String?
            val idArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.cancel(tagArg, idArg)
              listOf(null)
            } catch (exception: Throwable) {
              AndroidNotificationsPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
