// Autogenerated from Pigeon (v26.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class IosNativePigeonCodecReader: FlutterStandardReader {
}

private class IosNativePigeonCodecWriter: FlutterStandardWriter {
}

private class IosNativePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return IosNativePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return IosNativePigeonCodecWriter(data: data)
  }
}

class IosNativePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = IosNativePigeonCodec(readerWriter: IosNativePigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IosNativeHostApi {
  /// Sets UrlResourceValues.isExcludedFromBackup for the given file path.
  ///
  /// The file at this path must already exist,
  /// and be a regular file (not a directory).
  ///
  /// See doc:
  ///   https://developer.apple.com/documentation/foundation/urlresourcevalues/isexcludedfrombackup
  ///   https://developer.apple.com/documentation/foundation/optimizing-your-app-s-data-for-icloud-backup
  func setExcludedFromBackup(filePath: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IosNativeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { IosNativePigeonCodec.shared }
  /// Sets up an instance of `IosNativeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: IosNativeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Sets UrlResourceValues.isExcludedFromBackup for the given file path.
    ///
    /// The file at this path must already exist,
    /// and be a regular file (not a directory).
    ///
    /// See doc:
    ///   https://developer.apple.com/documentation/foundation/urlresourcevalues/isexcludedfrombackup
    ///   https://developer.apple.com/documentation/foundation/optimizing-your-app-s-data-for-icloud-backup
    let setExcludedFromBackupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.zulip.IosNativeHostApi.setExcludedFromBackup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setExcludedFromBackupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        do {
          try api.setExcludedFromBackup(filePath: filePathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setExcludedFromBackupChannel.setMessageHandler(nil)
    }
  }
}
