// Autogenerated from Pigeon (v25.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct NotificationDataFromLaunch {
  /// The raw payload that is attached to the notification,
  /// holding the information required to carry out the navigation.
  ///
  /// See [NotificationHostApi.getNotificationDataFromLaunch].
  var payload: [AnyHashable?: Any?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationDataFromLaunch? {
    let payload = pigeonVar_list[0] as! [AnyHashable?: Any?]

    return NotificationDataFromLaunch(
      payload: payload
    )
  }
  func toList() -> [Any?] {
    return [
      payload
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NotificationTapEvent {
  /// The raw payload that is attached to the notification,
  /// holding the information required to carry out the navigation.
  ///
  /// See [notificationTapEvents].
  var payload: [AnyHashable?: Any?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationTapEvent? {
    let payload = pigeonVar_list[0] as! [AnyHashable?: Any?]

    return NotificationTapEvent(
      payload: payload
    )
  }
  func toList() -> [Any?] {
    return [
      payload
    ]
  }
}

private class NotificationsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NotificationDataFromLaunch.fromList(self.readValue() as! [Any?])
    case 130:
      return NotificationTapEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NotificationsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NotificationDataFromLaunch {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NotificationTapEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NotificationsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NotificationsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NotificationsPigeonCodecWriter(data: data)
  }
}

class NotificationsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NotificationsPigeonCodec(readerWriter: NotificationsPigeonCodecReaderWriter())
}

var notificationsPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: NotificationsPigeonCodecReaderWriter());

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NotificationHostApi {
  /// Retrieves notification data if the app was launched by tapping on a notification.
  ///
  /// On iOS, this returns `launchOptions.remoteNotification`,
  /// which is the raw APNs data dictionary
  /// if the app launch was opened by a notification tap,
  /// else null. See Apple doc:
  ///   https://developer.apple.com/documentation/uikit/uiapplication/launchoptionskey/remotenotification
  ///
  /// On Android, this checks if the launch `intent` has the intent data uri
  /// starting with `zulip://notification` and has the extras bundle containing
  /// the notification open payload we set during creating the notification.
  /// Either returns the payload we set in the extras bundle, or null if the
  /// `intent` doesn't match the preconditions, meaning launch wasn't triggered
  /// by a notification.
  func getNotificationDataFromLaunch() throws -> NotificationDataFromLaunch?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NotificationHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NotificationsPigeonCodec.shared }
  /// Sets up an instance of `NotificationHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NotificationHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Retrieves notification data if the app was launched by tapping on a notification.
    ///
    /// On iOS, this returns `launchOptions.remoteNotification`,
    /// which is the raw APNs data dictionary
    /// if the app launch was opened by a notification tap,
    /// else null. See Apple doc:
    ///   https://developer.apple.com/documentation/uikit/uiapplication/launchoptionskey/remotenotification
    ///
    /// On Android, this checks if the launch `intent` has the intent data uri
    /// starting with `zulip://notification` and has the extras bundle containing
    /// the notification open payload we set during creating the notification.
    /// Either returns the payload we set in the extras bundle, or null if the
    /// `intent` doesn't match the preconditions, meaning launch wasn't triggered
    /// by a notification.
    let getNotificationDataFromLaunchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.zulip.NotificationHostApi.getNotificationDataFromLaunch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNotificationDataFromLaunchChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getNotificationDataFromLaunch()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNotificationDataFromLaunchChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class NotificationTapEventsStreamHandler: PigeonEventChannelWrapper<NotificationTapEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: NotificationTapEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.zulip.NotificationEventChannelApi.notificationTapEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<NotificationTapEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: notificationsPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
