org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true

# TODO(upstream) re-enable when upstream packages and other
#   third-party dependencies migrate to use/support
#   built-in Kotlin:
#     https://github.com/flutter/flutter/issues/185121
android.builtInKotlin=false

# TODO(upstream) re-enable when upstream migrates Flutter Android
#   Gradle plugin to use AGP "newDsl":
#     https://github.com/flutter/flutter/issues/181557
android.newDsl=false
