#!/usr/bin/env bash
set -euo pipefail

this_dir=${BASH_SOURCE[0]%/*}

# shellcheck source=tools/lib/deps.sh
. "${this_dir}"/../lib/deps.sh


flutter_tree=~/flutter

# Upstream's version calculation fails with a shallow clone,
# so instead clone with `--filter=blob:none`.
git clone --filter=blob:none -b main https://github.com/flutter/flutter "$flutter_tree"

TZ=UTC git -C "$flutter_tree" log -1 --format='%h | %ci | %s' --date=iso8601-local

echo "$flutter_tree"/bin >> "$GITHUB_PATH"

# The Flutter tool assumes the tip of tree is "origin/master"
# (or "upstream/master"):
#   https://github.com/flutter/flutter/issues/160626
# TODO(upstream): make workaround unneeded
git -C "$flutter_tree" update-ref refs/remotes/origin/master origin/main

# TODO(#2139): Temporarily pin the Flutter SDK in CI to use the same version
# in pubspec.yaml. Because currently there are multiple issues,
# see:
#   https://github.com/zulip/zulip-flutter/pull/2129#issuecomment-3878692297
#   https://github.com/zulip/zulip-flutter/pull/2129#issuecomment-3879280784
#   https://github.com/zulip/zulip-flutter/issues/2139#issuecomment-3895207862
flutter_commit=
pubspec_flutter_version || exit 1
git -C "$flutter_tree" reset --hard "$flutter_commit"
