#!/usr/bin/env bash
set -euo pipefail

this_dir=${BASH_SOURCE[0]%/*}

# shellcheck source=tools/lib/clone-flutter-sdk.sh
. "${this_dir}"/../lib/clone-flutter-sdk.sh


flutter_tree=~/flutter

clone_flutter_sdk "$flutter_tree"

echo "$flutter_tree"/bin >> "$GITHUB_PATH"
