// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// The notification content of the incoming push notification.
class NotificationContent {
  NotificationContent({
    required this.payload,
  });

  /// The raw APNs payload of the push notification.
  Map<Object?, Object?> payload;

  List<Object?> _toList() {
    return <Object?>[
      payload,
    ];
  }

  Object encode() {
    return _toList();  }

  static NotificationContent decode(Object result) {
    result as List<Object?>;
    return NotificationContent(
      payload: result[0]! as Map<Object?, Object?>,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NotificationContent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(payload, other.payload);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// The improved notification content that will be displayed to the user.
class ImprovedNotificationContent {
  ImprovedNotificationContent({
    required this.title,
    required this.subtitle,
    required this.body,
    required this.userInfo,
  });

  /// The new title to use for the notification.
  String title;

  /// The new subtitle to use for the notification.
  String subtitle;

  /// The new body to use for the notification.
  String body;

  /// The internal data to attach with the new notification.
  ///
  /// This replaces the raw APNs payload that was initially set from
  /// the remote push notification.
  Map<String, Object?> userInfo;

  List<Object?> _toList() {
    return <Object?>[
      title,
      subtitle,
      body,
      userInfo,
    ];
  }

  Object encode() {
    return _toList();  }

  static ImprovedNotificationContent decode(Object result) {
    result as List<Object?>;
    return ImprovedNotificationContent(
      title: result[0]! as String,
      subtitle: result[1]! as String,
      body: result[2]! as String,
      userInfo: (result[3]! as Map<Object?, Object?>).cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ImprovedNotificationContent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) && _deepEquals(subtitle, other.subtitle) && _deepEquals(body, other.body) && _deepEquals(userInfo, other.userInfo);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NotificationContent) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ImprovedNotificationContent) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NotificationContent.decode(readValue(buffer)!);
      case 130:
        return ImprovedNotificationContent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Exposes an API from Dart code which can be called from Swift code.
///
/// An implementation of this interface should be passed to
/// [ZulipBinding.instance.setupIosNotifFlutterApi] (which wraps
/// [IosNotifFlutterApi.setUp]) to initialize this Pigeon API.
abstract class IosNotifFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Corresponds to `NotificationService.didReceive` in NotificationService.swift.
  ///
  /// Invoked when NotificationService is triggered by a remote push
  /// notification, with the notification content which will contain the APNs
  /// payload.
  ///
  /// The returned result should be the improved notification content that
  /// will be displayed to the user.
  ///
  /// See docs: https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension/didreceive(_:withcontenthandler:)
  Future<ImprovedNotificationContent> didReceivePushNotification(NotificationContent content);

  static void setUp(IosNotifFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.zulip.IosNotifFlutterApi.didReceivePushNotification$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NotificationContent arg_content = args[0]! as NotificationContent;
          try {
            final ImprovedNotificationContent output = await api.didReceivePushNotification(arg_content);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
