// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class NotificationDataFromLaunch {
  NotificationDataFromLaunch({
    required this.payload,
  });

  /// The raw payload that is attached to the notification,
  /// holding the information required to carry out the navigation.
  ///
  /// See [NotificationHostApi.getNotificationDataFromLaunch].
  Map<Object?, Object?> payload;

  List<Object?> _toList() {
    return <Object?>[
      payload,
    ];
  }

  Object encode() {
    return _toList();  }

  static NotificationDataFromLaunch decode(Object result) {
    result as List<Object?>;
    return NotificationDataFromLaunch(
      payload: result[0]! as Map<Object?, Object?>,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NotificationDataFromLaunch || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(payload, other.payload);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

sealed class NotificationTapEvent {
}

/// On iOS, an event emitted when a notification is tapped.
///
/// See [notificationTapEvents].
class IosNotificationTapEvent extends NotificationTapEvent {
  IosNotificationTapEvent({
    required this.payload,
  });

  /// The iOS APNs payload of the notification.
  ///
  /// See [notificationTapEvents].
  Map<Object?, Object?> payload;

  List<Object?> _toList() {
    return <Object?>[
      payload,
    ];
  }

  Object encode() {
    return _toList();  }

  static IosNotificationTapEvent decode(Object result) {
    result as List<Object?>;
    return IosNotificationTapEvent(
      payload: result[0]! as Map<Object?, Object?>,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IosNotificationTapEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(payload, other.payload);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// On Android, an event emitted when a notification is tapped.
///
/// See [notificationTapEvents].
class AndroidNotificationTapEvent extends NotificationTapEvent {
  AndroidNotificationTapEvent({
    required this.dataUrl,
  });

  /// The intent data URL of the notification.
  ///
  /// This is an internal URL that is generated using
  /// `NotificationOpenPayload.buildAndroidNotificationUrl` while creating the
  /// notification during `NotificationDisplayManager._onNotifPayloadNewMessage`.
  ///
  /// See [notificationTapEvents].
  String dataUrl;

  List<Object?> _toList() {
    return <Object?>[
      dataUrl,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidNotificationTapEvent decode(Object result) {
    result as List<Object?>;
    return AndroidNotificationTapEvent(
      dataUrl: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidNotificationTapEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(dataUrl, other.dataUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NotificationDataFromLaunch) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is IosNotificationTapEvent) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidNotificationTapEvent) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NotificationDataFromLaunch.decode(readValue(buffer)!);
      case 130:
        return IosNotificationTapEvent.decode(readValue(buffer)!);
      case 131:
        return AndroidNotificationTapEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class NotificationHostApi {
  /// Constructor for [NotificationHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NotificationHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Retrieves notification data if the app was launched by tapping on a notification.
  ///
  /// Returns `launchOptions.remoteNotification`,
  /// which is the raw APNs data dictionary
  /// if the app launch was opened by a notification tap,
  /// else null. See Apple doc:
  ///   https://developer.apple.com/documentation/uikit/uiapplication/launchoptionskey/remotenotification
  Future<NotificationDataFromLaunch?> getNotificationDataFromLaunch() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.zulip.NotificationHostApi.getNotificationDataFromLaunch$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as NotificationDataFromLaunch?;
  }
}

/// An event stream that emits a notification payload
/// when a notification is tapped.
///
/// On iOS, emits [IosNotificationTapEvent] when
/// `userNotificationCenter(_:didReceive:withCompletionHandler:)` gets
/// called, indicating that the user has tapped on a notification. The
/// emitted event carries a payload which will be the raw APNs data
/// dictionary from the `UNNotificationResponse` passed to that method.
///
/// On Android, emits [AndroidNotificationTapEvent] when the initial launch
/// intent (`MainActivity.intent`) or the intent received via
/// `MainActivity.onNewIntent` is an ACTION_VIEW intent and the associated
/// data URL has the "zulip" scheme, and "notification" authority. The
/// emitted event will carry the intent data URL.
Stream<NotificationTapEvent> notificationTapEvents( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel notificationTapEventsChannel =
      EventChannel('dev.flutter.pigeon.zulip.NotificationEventChannelApi.notificationTapEvents$instanceName', pigeonMethodCodec);
  return notificationTapEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as NotificationTapEvent;
  });
}
    
