#!/usr/bin/env bash
set -euo pipefail

this_dir=${BASH_SOURCE[0]%/*}

# shellcheck source=tools/lib/ensure-shell-deps.sh
. "${this_dir}"/lib/ensure-shell-deps.sh

root_dir=$(readlink -f "${this_dir}"/..)

exec "${root_dir}"/android/gradlew -p "${root_dir}"/android "$@"
