#!/usr/bin/env bash
set -euo pipefail

this_dir=${BASH_SOURCE[0]%/*}

# shellcheck source=tools/lib/git.sh
. "${this_dir}"/lib/git.sh


# One-time setup to let git submodule + flutter SDK know that we're
# using the main channel (main branch).
# We should do a quick check that there's no changes.
if ! submodule_is_clean "vendor/flutter" ; then
    echo >&2 "There are changes in the 'vendor/flutter' tree or it is not initialized."
    echo >&2 "Please run 'git submodule update --init' then run this script again."
    exit 1
fi

git -C vendor/flutter checkout -B main HEAD
